# This is a basic workflow to help you get started with Actions

name: DiraRK

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          echo `id`
          sudo apt-get install jq
          wget https://github.com/HCL-TECH-SOFTWARE/appscan-issue-gateway/releases/download/v0.3.1/appscan-issue-gateway-0.3.1.zip
          unzip appscan-issue-gateway-0.3.1.zip
          echo `pwd`
          ls -ltr
          cd appscan-issue-gateway-0.3.1
          chmod -R 775 appscan-issue-gateway
          cd appscan-issue-gateway
          ls -ltr
          mv ../../*.sh .
          mv ../../*.json .
          chmod 775 *.sh
          ls -ltr
          
          nohup ./appscangateway.sh nohup.out 2> nohup.err < /dev/null &
          sleep 10
      - name: Run a multi-line script
        run: |
           cd appscan-issue-gateway-0.3.1/appscan-issue-gateway
           ls -ltra
           sh ./postjob.sh > RK.txt
           ls -ltr
           cat RK.txt
           echo "Kaushal Check"
           sed -n '2p' RK.txt | cut -d "\"" -f 4 > DK.txt
           ls -ltr
           cat DK.txt
           echo " Kaushal Checked"
           sh ./getjob.sh `cat DK.txt`
           
     
          
             



